# Generated by Django 4.2.4 on 2023-09-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_converter_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='currency_image_url',
        ),
    ]
