# Generated by Django 4.2.5 on 2023-09-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_converter_app', '0002_remove_currency_currency_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
